clean:
  build: ["<%= props.targetPath %>"]

uglify:
  options:
    compress:
      global_defs:
        DEBUG: false
      dead_code: true
  build:
    files:
      -
        dest: '<%= props.targetPath %>/scripts.<%= props.buildId %>.js'
        src:
          - '<%= props.assetsPath %>/Javascript/jquery.js'
          - '<%= props.assetsPath %>/Javascript/bootstrap.js'

recess:
  options:
    compile: true
  build:
    options:
      compress: true
    files:
      -
        dest: '<%= props.targetPath %>/styles.<%= props.buildId %>.css'
        src:
          - '<%= props.lessFile %>'

compress:
  build:
    options:
      level: 9
      mode: gzip
    files:
      -
        expand: true
        flatten: true
        cwd: '<%= props.targetPath %>'
        src: ['*.css']
        dest: '<%= props.targetPath %>/'
        ext: '.<%= props.buildId %>.css.gz'
      -
        expand: true
        flatten: true
        cwd: '<%= props.targetPath %>'
        src: ['*.js']
        dest: '<%= props.targetPath %>/'
        ext: '.<%= props.buildId %>.js.gz'
  deploy:
    options:
      mode: 'tgz'
      archive: 'current.tgz'
    files: []

sftp:
  options:
    createDirectories: true
    path: '/tmp/current/'
    host: '<%= props.ssh.host %>'
    username: '<%= props.ssh.username %>'
    privateKey: '<%= props.ssh.privateKey %>'
    passphrase: '<%= props.ssh.passphrase %>'
  deploy:
    files:
      -
        src: 'current.tgz'
        dist: 'current.tgz'

sshexec:
  options:
    host: '<%= props.ssh.host %>'
    username: '<%= props.ssh.username %>'
    privateKey: '<%= props.ssh.privateKey %>'
    passphrase: '<%= props.ssh.passphrase %>'
  unpack:
    command: 'cd /tmp/current && tar xzf current.tgz && rm current.tgz'
  replace:
    command: 'mv <%= props.deploy.remoteTarget %>/typo3conf/ext <%= props.deploy.remoteTarget %>/typo3conf/ext_`date +%Y-%m-%d_%H-%M-%S` && mv /tmp/current <%= props.deploy.remoteTarget %>/typo3conf/ext'
  tempcached:
    command: 'rm -rf <%= props.deploy.remoteTarget %>/typo3temp/Cache/Code/cache_core'
  dbtables:
    command: '<%= props.deploy.remoteTarget %>/typo3/cli_dispatch.phpsh extbase databaseapi:databasecompare 1,2,3,4,5,7'
  clearcaches:
    command: '<%= props.deploy.remoteTarget %>/typo3/cli_dispatch.phpsh extbase cacheapi:clearallexceptpagecache'
